name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip \
            openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev cmake libffi-dev libssl-dev \
            libncurses-dev libncursesw-dev libtinfo-dev

      - name: Install Buildozer & Cython
        run: |
          python3 -m pip install --upgrade pip
          pip install --user buildozer cython==0.29.33

      - name: Add ~/.local/bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Initialize Buildozer
        run: buildozer init

      - name: Build Android APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-debug.apk
          path: bin/*.apk
