name: Build APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev libssl-dev cmake automake build-essential libtinfo6

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;33.0.0"

      - name: Setup Android NDK (r21e)
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false

      - name: Install Python build tools
        run: |
          pip install --upgrade pip
          pip install Cython virtualenv
          pip install buildozer

      - name: Build APK with Buildozer
        run: |
          export ANDROID_NDK_HOME="${{ steps.setup-ndk.outputs.ndk-path }}"
          yes | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
