name: Android Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade Cython virtualenv buildozer python-for-android

      - name: Manually install Android cmdline-tools and accept licenses
        run: |
          SDK_DIR=$HOME/.buildozer/android/platform/android-sdk
          mkdir -p "$SDK_DIR/cmdline-tools"
          cd "$SDK_DIR/cmdline-tools"
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          mv cmdline-tools latest

          # Add sdkmanager to PATH and install build-tools and platform-tools
          export PATH=$SDK_DIR/cmdline-tools/latest/bin:$PATH
          yes | $SDK_DIR/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_DIR "platform-tools" "platforms;android-31" "build-tools;31.0.0"

          # Accept licenses
          mkdir -p $SDK_DIR/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $SDK_DIR/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $SDK_DIR/licenses/android-sdk-preview-license

      - name: Build APK
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          export BUILD_LOG_LEVEL=2
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
