name: ساخت APK اندروید با Buildozer
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: نصب وابستگی‌های سیستمی
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            openjdk-11-jdk \
            unzip \
            zip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libportmidi-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libmtdev-dev \
            libgtk-3-dev \
            libgstreamer1.0-dev \
            libpulse-dev

      - name: Upgrade pip و نصب وابستگی‌های pip
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.33 kivy arabic_reshaper python-bidi

      - name: ساخت نهایی APK
        run: |
          buildozer android debug

      - name: ذخیره APK به عنوان artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
