name: Build
on:
  push:

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # نصب بسته‌ی distutils برای رفع خطای ModuleNotFoundError
          sudo apt-get install -y python3-distutils python3-dev libssl-dev libffi-dev :contentReference[oaicite:2]{index=2}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install buildozer :contentReference[oaicite:3]{index=3}

      - name: Build with Buildozer
        run: |
          buildozer android debug :contentReference[oaicite:4]{index=4}
        working-directory: .
        env:
          # متغیرهای Android SDK را می‌توانید از Secrets وارد کنید:
           ANDROIDSDK_ROOT: ${{ secrets.ANDROIDSDK_ROOT }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            ./.buildozer/android/app/bin/*.apk
            ./.buildozer/android/app/bin/*.aab :contentReference[oaicite:5]{index=5}
