name: Android Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade Cython virtualenv buildozer python-for-android

      - name: Build APK
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
          export ANDROID_SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
          export ANDROID_NDK_HOME="$HOME/.buildozer/android/platform/android-ndk-r25b"
          export ANDROID_HOME="$ANDROID_SDK_ROOT"
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
          yes | buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
