name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            software-properties-common \
            openjdk-17-jdk \
            zip unzip \
            git \
            python3-distutils \
            python3-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev

      - name: Install Buildozer & dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip install buildozer cython

      - name: Cache Buildozer artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.local/share/buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Build APK
        run: |
          buildozer android debug
        working-directory: .

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: |
            ./.buildozer/android/platform/build/dists/*/bin/*.apk
