name: Build APK                     # نام workflow
on:
  push:
    branches: [main]                # اجرا هنگام push به شاخه‌ی main

jobs:
  build:
    runs-on: ubuntu-latest         # محیط اجرا (Ubuntu)

    steps:
      - name: دریافت کد پروژه     # چک‌اوت از مخزن (کد منبع)
        uses: actions/checkout@v3

      - name: ساخت با Buildozer   # اجرای Buildozer (ساخت APK)
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: 'yes | buildozer android debug'  # پذیرش خودکار لایسنس و ساخت APK

      - name: آپلود فایل APK      # ذخیره‌ی خروجی APK به عنوان artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ steps.buildozer.outputs.filename }}  # مسیر فایل APK تولید شده
