name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Android Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -L https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip \
            -o cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest

      - name: Add sdkmanager to PATH
        run: echo "$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools cython
          pip install buildozer

      - name: Clean previous build
        run: buildozer android clean

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fencing-app-apk
          path: bin/*.apk
