name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            m4 \
            autoconf \
            automake \
            libtool \
            libtool-bin \
            gettext \
            autopoint \
            pkgconf \
            build-essential \
            git \
            openjdk-11-jdk \
            unzip \
            zip \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            libncurses-dev \
            libtinfo-dev \
            libsdl2-dev

      - name: Upgrade pip and install Python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.33 kivy arabic_reshaper python-bidi

      - name: Add Buildozer to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Clean previous build artifacts
        run: rm -rf ./.buildozer

      - name: Build Android APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fencingapp-debug
          path: bin/*.apk
