name: Android Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # --- مرحله تنظیم Android SDK ---
      # اینجا مشکل در دانلود خود این اکشن است
      - name: Setup Android SDK
        uses: android-action/setup-android@v3 # <--- مشکل در اینجا
        with:
          build-tools: '34.0.0'
          sdk-components: platforms;android-34

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade Cython virtualenv buildozer python-for-android

      - name: Build APK
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          export JAVA_HOME="/usr/lib/jvm/temurin-17-jdk-amd64"
          export BUILD_LOG_LEVEL=2
          yes | buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
