name: Build

on:
  push:

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Enable universe repo and install system dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y \
            python3.12-distutils \
            python3-dev \
            zip unzip \
            openjdk-17-jdk \
            libssl-dev \
            libffi-dev \
            libsqlite3-dev \
            git

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            ./.buildozer/android/platform/build/dists/*/bin/*.apk
