name: Build Kivy Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-11-jdk \
            python3-venv python3-dev libffi-dev libssl-dev \
            autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Buildozer & python-for-android
        run: |
          python3 -m pip install --upgrade pip setuptools cython
          pip install buildozer python-for-android

      - name: Install Android SDK & accept licenses
        run: |
          yes | buildozer android sdk --sdk --ndk --licenses

      - name: Clean previous build
        run: buildozer android clean

      - name: Build APK
        run: |
          buildozer android debug --verbose

      - name: List output APK(s)
        run: find . -type f -name "*.apk"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fencing-app-apk
          path: bin/*.apk
